# Generated by Django 2.2.28 on 2023-03-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerateapp', '0002_userprofile_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='publisher',
        ),
    ]
