# Generated by Django 2.2.28 on 2023-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerateapp', '0006_auto_20230323_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, default='game_images/no_image.jpg', upload_to='game_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
